import { Metadata } from 'next'
import { Container, Card, CardContent } from '@repo/ui'
import { FileText } from 'lucide-react'

export const metadata: Metadata = {
  title: 'Terms of Service | Flowtaris AI',
  description: 'Flowtaris AI Terms of Service. Information about your rights and responsibilities when using our services.',
}

export default function TermsPage() {
  return (
    <div className="flex flex-col flex-1 w-full pt-32 pb-24">
      <Container size="lg">
        <div className="mb-12">
          <div className="inline-flex items-center gap-2 px-3.5 py-1.5 rounded-full border border-white/[0.08] bg-white/[0.02] mb-6">
            <FileText className="h-4 w-4 text-brand-cyan-400" />
            <span className="text-[10px] font-bold tracking-[0.16em] text-white/50 uppercase">Legal & Compliance</span>
          </div>
          <h1 className="text-display-lg text-white mb-6">Terms of Service</h1>
          <p className="text-headline-sm text-neutral-400">
            Effective Date: September 1, 2026
          </p>
        </div>

        <Card className="glass-card">
          <CardContent className="p-8 md:p-12 prose prose-invert max-w-none prose-p:text-neutral-300 prose-headings:text-white prose-a:text-[#E8A020]">

            <h2>1. Acceptance of Terms & Master Services Agreement (MSA)</h2>
            <p>
              These Terms of Service govern the use of the Flowtaris AI platform and website. For enterprise customers, these terms operate in conjunction with your specific Master Services Agreement (MSA) and Service Level Agreement (SLA). In the event of a conflict between these terms and your executed MSA, the terms of the MSA shall prevail.
            </p>

            <h2>2. Enterprise Service Level Agreements (SLA)</h2>
            <p>
              Flowtaris AI guarantees a <strong>99.99% uptime</strong> for our core automation engine and API gateways. Service credits are automatically applied for any downtime exceeding this threshold, as detailed in your MSA. Scheduled maintenance windows will be communicated to your administrative contacts with a minimum of 48 hours' notice.
            </p>

            <h2>3. Intellectual Property: You Own Your AI Outputs</h2>
            <p>
              Flowtaris AI retains all intellectual property rights to our proprietary automation platform, OCR engines, LLM orchestration layers, and software code. However, <strong>you retain 100% ownership of all data inputted into the system and all outputs generated by the AI on your behalf.</strong> Flowtaris AI claims no rights to your financial records, generated analyses, or conversational ERP interactions.
            </p>

            <h2>4. Acceptable Use & API Rate Limiting</h2>
            <p>
              Access to the Flowtaris AI platform and our ERP integration endpoints is subject to fair use and programmatic rate limiting to protect system stability. Customers agree not to:
            </p>
            <ul>
              <li>Reverse engineer, decompile, or attempt to extract the source code of our models.</li>
              <li>Use the platform to process data that violates international sanctions or anti-money laundering (AML) regulations.</li>
              <li>Attempt to bypass security controls, RBAC permissions, or tenant isolation mechanisms.</li>
            </ul>

            <h2>5. Confidentiality & Non-Disclosure</h2>
            <p>
              Both parties agree to strict confidentiality regarding proprietary business processes, financial data, and technical integration details. Flowtaris AI employees operate under stringent NDAs and undergo rigorous background checks. We will never publicly disclose your usage of our platform without explicit, written marketing consent.
            </p>

            <h2>6. Limitation of Liability</h2>
            <p>
              While our AI agents operate with deterministic guardrails and human-in-the-loop (HITL) fallback mechanisms, Flowtaris AI acts as an augmentation layer to your finance team. Your organization remains ultimately responsible for the final execution and approval of financial transactions within your ERP (e.g., executing a wire transfer in NetSuite). Our liability is limited to the extent outlined in your enterprise MSA.
            </p>

            <h2>7. Contact Legal</h2>
            <p>
              For MSA negotiations, SLA inquiries, or general legal questions, please contact our counsel:
              <br /><br />
              <strong>Flowtaris Legal & Compliance</strong><br />
              Email: legal@flowtaris.com
            </p>
          </CardContent>
        </Card>
      </Container>
    </div>
  )
}
